/**
 * Created by JohnBae on 2/13/17.
 */
export const DELETE_AT_LAYOUT = "DELETE_AT_LAYOUT";
export const DELETE_AT_SESSION = "DELETE_AT_SESSION";
export const MODIFY_AT_LAYOUT = "MODIFY_AT_LAYOUT";
export const MODIFY_AT_SESSION = "MODIFY_AT_SESSION";
export const MODIFY_AT_SETTING = "MODIFY_AT_SETTING";
export const SET_LAYOUT = "SET_LAYOUT";
export const SET_SESSION = "SET_SESSION";
export const SET_SETTING = "SET_SETTING";
export const ADD_STORED_LAYOUT = "DELETE_STORED_LAYOUT";
export const RENAME_STORED_LAYOUT = "RENAME_STORED_LAYOUT";
export const DELETE_STORED_LAYOUT = "DELETE_STORED_LAYOUT";

